image: gitlab/dind:latest
stages:
  - test

deploy_test:
  stage: test
  only:
    - "develop"
  when: manual
  environment:
    name: test
    url: http://stg-mybl.cyberlogitec.com.vn:8000
  script:
    - echo "Sending Deployment Trigger"
    - 'curl -v -d "commit_id=${CI_COMMIT_SHA:0:8}" -H "Authorization: ${DEPLOY_TOKEN}" -X POST http://stg-mybl.cyberlogitec.com.vn:8000/pipeline/test/portal'
