image: gitlab/dind:latest
stages:
  - develop
  - release
  
deploy_development:
  stage: develop
  only:
    - "develop"
  when: manual
  environment:
    name: development
  script:
    - echo "Deploy for development"
    - curl -v -X GET http://si-automation.dounets.com:8804/exec/pipeline/myBL/portal?ci_commit=${CI_COMMIT_SHA:0:7}


deploy_release:
  stage: release
  only:
    - "release"
  when: manual
  environment:
    name: test
  script:
    - echo "Deploy for release"
    - curl -v -X GET http://si-automation.dounets.com:8804/exec/pipeline/myBL/portal?ci_commit=${CI_COMMIT_SHA:0:7}
