stages:
  - develop
  - test
  - release
  - staging
  - production

deploy_development:
  stage: develop
  only:
    - "develop"
  when: manual
  allow_failure: false
  environment:
    name: development
  script:
    - echo "${GITLAB_USER_LOGIN} merged commit ${CI_COMMIT_SHA:0:8} to develop branch"
    - 'curl -f -d "commit_id=${CI_COMMIT_SHA:0:8}&triggerer=${GITLAB_USER_LOGIN}" -H "Authorization: ${DEPLOY_TOKEN}" -X POST http://blink-dev.one-line.com/pipeline/development/portal'

deploy_test:
  stage: test
  only:
    - "test"
  when: manual
  allow_failure: false
  environment:
    name: test
    url: http://blink-dev.one-line.com
  script:
    - echo "${GITLAB_USER_LOGIN} sending Deployment trigger to Test site"
    - 'curl -f -d "commit_id=${CI_COMMIT_SHA:0:8}&triggerer=${GITLAB_USER_LOGIN}" -H "Authorization: ${DEPLOY_TOKEN}" -X POST http://blink-dev.one-line.com/pipeline/test/portal'

deploy_release:
  stage: release
  only:
    - "release"
  when: manual
  allow_failure: false
  environment:
    name: release
  script:
    - echo "${GITLAB_USER_LOGIN} merged commit ${CI_COMMIT_SHA:0:8} to release branch"
    - 'curl -f -d "commit_id=${CI_COMMIT_SHA:0:8}&triggerer=${GITLAB_USER_LOGIN}" -H "Authorization: ${DEPLOY_TOKEN}" -X POST http://blink-dev.one-line.com/pipeline/release/portal'

deploy_staging:
  stage: staging
  only:
    - "staging"
  when: manual
  allow_failure: false
  environment:
    name: staging
    url: http://blink-stg.one-line.com
  script:
    - echo "${GITLAB_USER_LOGIN} sending Deployment trigger to Staging site"
    - 'curl -f -d "commit_id=${CI_COMMIT_SHA:0:8}&triggerer=${GITLAB_USER_LOGIN}" -H "Authorization: ${DEPLOY_TOKEN}" -X POST http://blink-stg.one-line.com/pipeline/staging/portal'

deploy_production:
  stage: production
  only:
    - "production"
  when: manual
  allow_failure: false
  environment:
    name: production
    url: https://blink.one-line.com
  script:
    - echo "${GITLAB_USER_LOGIN} sending Deployment trigger to Production site"
    - 'curl -f -d "commit_id=${CI_COMMIT_SHA:0:8}&triggerer=${GITLAB_USER_LOGIN}" -H "Authorization: ${DEPLOY_TOKEN}" -X POST https://blink.one-line.com/pipeline/production/portal'