image: gitlab/dind:latest
stages:
  - develop
  - release

deploy_development:
  stage: develop
  only:
    - "develop"
  when: manual
  environment:
    name: development
  script:
    - echo "Deploying stg-mybl.cyberlogitec.com.vn:8000"
    - 'curl -v -d "commit_id=${CI_COMMIT_SHA:0:8}" -H "Authorization: ${DEPLOY_TOKEN}" -X POST http://stg-mybl.cyberlogitec.com.vn:8000/pipeline/test/portal'
