version: '3.7'
services:
  nginx:
    container_name: blink-nginx-${ENV}
    build: ./gateway/
    image: nginx:latest
    restart: always
    env_file:
      - .env
    command:
      [
        "/bin/bash",
        "-c",
        "envsubst '$$ENV $$API_HOST $$APP_HOST $$PORTAL_PORT $$DEPLOYER_HOST' < /etc/nginx/conf.d/nginx.template > /etc/nginx/conf.d/nginx.conf && nginx -g 'daemon off;'",
      ]
    ports:
      - ${GATEWAY_PORT}:80
    volumes:
      - "./gateway/:/etc/nginx/conf.d"
    healthcheck:
      test: exit 0
    depends_on:
      - portal-service

  portal-service:
    container_name: blink-portal-${ENV}
    image: blink-portal:1.2
    restart: always
    working_dir: /blink/portal
    command: "./scripts/start.sh"
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    # environment:
    #   - PORT=${PORTAL_PORT}
    volumes:
      - ./:/blink/portal
